<?php

namespace UploaderBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileRepository extends \Doctrine\ORM\EntityRepository
{
}
