<?php

namespace UserBundle\Repository;

use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUsersQuery($filters = []){
        $qb = $this->_em->createQueryBuilder();
         $qb->select('u')
             ->from(User::class,'u');

        return $qb->getQuery();
    }

}
